# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Estado.create(descricao: 'Rondonia', sigla: 'RO', regiao: 'Norte')
Estado.create(descricao: 'Acre', sigla: 'AC', regiao: 'Norte')
Estado.create(descricao: 'Amazonas', sigla: 'AM', regiao: 'Norte')
Estado.create(descricao: 'Roraima', sigla: 'RR', regiao: 'Norte')
Estado.create(descricao: 'Para', sigla: 'PA', regiao: 'Norte')
Estado.create(descricao: 'Amapa', sigla: 'AP', regiao: 'Norte')
Estado.create(descricao: 'Tocantins', sigla: 'TO', regiao: 'Norte')
Estado.create(descricao: 'Maranhao', sigla: 'MA', regiao: 'Nordeste')
Estado.create(descricao: 'Piaui', sigla: 'PI', regiao: 'Nordeste')
Estado.create(descricao: 'Ceara', sigla: 'CE', regiao: 'Nordeste')
Estado.create(descricao: 'Rio Grande do Norte', sigla: 'RN', regiao: 'Nordeste')
Estado.create(descricao: 'Paraiba', sigla: 'PB', regiao: 'Nordeste')
Estado.create(descricao: 'Pernanbuco', sigla: 'PE', regiao: 'Nordeste')
Estado.create(descricao: 'Alagoas', sigla: 'AL', regiao: 'Nordeste')
Estado.create(descricao: 'Sergipe', sigla: 'SE', regiao: 'Nordeste')
Estado.create(descricao: 'Bahia', sigla: 'BA', regiao: 'Nordeste')
Estado.create(descricao: 'Minas Gerais', sigla: 'MG', regiao: 'Sudeste')
Estado.create(descricao: 'Espirito Santo', sigla: 'ES', regiao: 'Sudeste')
Estado.create(descricao: 'Rio de Janeiro', sigla: 'RJ', regiao: 'Sudeste')
Estado.create(descricao: 'Sao Paulo', sigla: 'SP', regiao: 'Sudeste')
Estado.create(descricao: 'Parana', sigla: 'PR', regiao: 'Sul')
Estado.create(descricao: 'Santa Catarina', sigla: 'SC', regiao: 'Sul')
Estado.create(descricao: 'Rio Grande do Sul', sigla: 'RS', regiao: 'Sul')
Estado.create(descricao: 'Mato Grosso do Sul', sigla: 'MS', regiao: 'Centro-Oeste')
Estado.create(descricao: 'Mato Grosso', sigla: 'MT', regiao: 'Centro-Oeste')
Estado.create(descricao: 'Goias', sigla: 'GO', regiao: 'Centro-Oeste')
Estado.create(descricao: 'Distrito-Federal', sigla: 'DF', regiao: 'Centro-Oeste')
Estado.create(descricao: 'Outro', sigla: 'OT', regiao: 'Outro')

Raca.create(descricao: 'Branca')
Raca.create(descricao: 'Morena')
Raca.create(descricao: 'Parda')
Raca.create(descricao: 'Negra')
Raca.create(descricao: 'Preta')
Raca.create(descricao: 'Amarela')
Raca.create(descricao: 'Indigina')
Raca.create(descricao: 'Outras')

EstadoCivil.create(descricao: 'Solteiro(a)')
EstadoCivil.create(descricao: 'Casado(a)')
EstadoCivil.create(descricao: 'Divorciado(a)')
EstadoCivil.create(descricao: 'Viuvo(a)')

GrauInstrucao.create(descricao: 'Analfabeto')
GrauInstrucao.create(descricao: 'Ensino fundamental incompleto')
GrauInstrucao.create(descricao: 'Ensino fundamental completo')
GrauInstrucao.create(descricao: 'Ensino medio incompleto')
GrauInstrucao.create(descricao: 'Ensino medio completo')
GrauInstrucao.create(descricao: 'Ensino superior incompleto')
GrauInstrucao.create(descricao: 'Ensino superior completo')
GrauInstrucao.create(descricao: 'Mestrado')
GrauInstrucao.create(descricao: 'Doutorado')


Role.create(descricao: 'ADMIN')
Role.create(descricao: 'EDITOR')
Role.create(descricao: 'VISUALIZADOR')
